KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="dainh-kafka"
    password="dainh-kafka-secret"
    user_dainh-kafka="dainh-kafka-secret"
    user_dainh-client="dainh-client-secret";
};